import { getUnsplashUrls } from "../utilities/getUnsplashUrls";
import { getGoogleVisionLabels } from "../utilities/getGoogleVisionLabels";
import { getImages } from "../utilities/getImages";
import Image from "../entities/Image";
export class ImageRepository {
	public async analyze(keyword: string, labels: string[]): Promise<Image> {
		//get url from unsplash Api
		const urls = await getUnsplashUrls(keyword);
		//matching images labels with labels generated by google cloud vision
		const urlsLabels = await getGoogleVisionLabels(labels, urls);
		//Create the object images to send it in response
		const images = await getImages(keyword, urlsLabels);
		return images;
	}
}
