import { getUnsplashUrls } from "../utilities/getUnsplashUrls";
import { getGoogleVisionLabels } from "../utilities/getGoogleVisionLabels";
import { RequestParams, Response } from "../entities";

export class ImageRepository {
	public async analyze(params: RequestParams): Promise<Response> {
		const { keyword, labels } = params;

		// get url from unsplash Api
		const urls = await getUnsplashUrls(keyword);

		// matching images labels with labels generated by google cloud vision
		const urlsLabels = await getGoogleVisionLabels(labels, urls);

		return {
			keyword,
			matches: urlsLabels,
		};
	}
}
